import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import "./globals.css";
import { cn } from "@/lib/tailwind";
import { montserrat } from "@/fonts/Montserrat";
import { Navigation } from "@/components/layout/nav";
import { Footer } from "@/components/layout/footer";
import { cookies } from "next/headers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const currentLocale = cookieStore.get("locale")?.value || "en";
  return (
    <html lang="en">
      <body
        className={cn(
          montserrat.className,
          montserrat.variable,
          "flex flex-col relative items-center antialiased"
        )}
      >
        <NextIntlClientProvider>
          {/* <Navigation local={currentLocale} /> */}
          <div className="relative z-10">{children}</div>
          {/* <Footer /> */}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
